services:
  mongodb:
    image: mongodb/mongodb-community-server:8.0-ubi8
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    env_file:
      - .env.prod
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}

  app:
    build:
      context: ../server
    restart: unless-stopped
    depends_on:
      - mongodb
    env_file:
      - .env.prod
    environment:
      MONGO_URL: mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@mongodb:27017/${MONGO_DB}?authSource=admin
    ports:
      - '5000'

  web-client:
    build:
      context: ../web-client
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    restart: unless-stopped
    ports:
      - '3000'

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - app
      - web-client
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - default

volumes:
  mongo_data: