services:
  mongodb:
    image: mongodb/mongodb-community-server:8.0-ubi8
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass

  app:
    build:
      context: ../server
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      FRONTEND_URL: http://158.160.148.51:3000
      MONGO_URL: mongodb://user:pass@mongodb:27017/glossary?authSource=admin
      NODE_ENV: production
      LOG_LEVEL: info
    ports:
      - '5000:5000'

  web-client:
    build:
      context: ../web-client
      args:
        NEXT_PUBLIC_API_URL: http://158.160.148.51:5000
    restart: unless-stopped
    ports:
      - '3000:3000'

volumes:
  mongo_data: